name: HashCatcher Release Pipeline

on:
  push:
    tags:
      - "v*"

jobs:

  linux-build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            python3 \
            python3-pip \
            python3-pyside6 \
            hcxtools \
            hashcat \
            dpkg-dev

      - name: Install Python Packages
        run: |
          pip install pyinstaller

      - name: Build Linux Executable
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            src/main.py \
            --name HashCatcher

      - name: Create dist folder
        run: |
          mkdir -p dist

      - name: Copy executable
        run: |
          cp dist/HashCatcher dist/hashcatcher-linux

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: hashcatcher-linux
          path: dist/hashcatcher-linux

  windows-build:
    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python Packages
        run: |
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller ^
            --onefile ^
            --windowed ^
            src/main.py ^
            --name HashCatcher

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: hashcatcher-windows
          path: dist/HashCatcher.exe

  macos-build:
    runs-on: macos-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python Packages
        run: |
          pip3 install pyinstaller

      - name: Build macOS App
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            src/main.py \
            --name HashCatcher

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: hashcatcher-macos
          path: dist/HashCatcher
